export const STATUS = [
  "telah lulus",
  "sedang pendidikan",
  "cuti",
  "akan pendidikan",
];
export const ROLES = ["admin", "user"];
export const KSM = [
  "Ilmu Kesehatan Anak",
  "Orthopedi & Traumatologi",
  "Kardiologi",
  "Urologi",
  "Bedah Saraf",
  "Obgyn",
  "Neurologi",
  "Ilmu Penyakit Dalam",
  "IKFR",
  "Bedah Thoraks Vaskuler",
  "Anestesi & Terapi Intensif",
  "THT-KL",
  "Bedah Anak",
  "Patologi Klinik",
  "Radiologi",
];
export const FELLOWSHIP = [
  "Neonatologi",
  "Electrophysiology and Pacing (Aritmia)",
  "Emergensi & Terapi Intensif Anak",
  "Orthopaedi Sports Injury",
  "Orthopaedi Shoulder and Elbow",
  "Orthopaedi Advanced Trauma",
  "Orthopaedi Hand, Upper Limb and Microsurgery",
  "Orthopaedi Pediatric",
  "Orthopaedi Foot and Ankle",
  "Orthopaedi Spine",
  "Hand, Upper Limb and Microsurgery",
  "Foot and Ankle",
  "Sport Injury",
  "Hip and Knee",
  "Kardiologi Intervensi",
  "Rekontruksi Urethra Pria",
  "Urologi Pediatrik",
  "Urologi Onkologi",
  "Neurovaskuler",
  "Neuro Pediatric",
  "Infertilitas",
  "Endosckopi Ginekologi Reproduksi dan Fertilitas",
  "ObgynSosial",
  "Neurobehavior",
  "Nyeri Kepala",
  "Neuroinfeksi",
  "Neurofisiologi Klinis",
  "Endoskopi Saluran Cerna",
  "Dialisis Dasar",
  "Onkologi",
  "Rehabilitasi Stroke",
  "Pembedahan Katup Jantung & CABG Risti",
  "Bedah Jantung Dewasa",
  "Adult Cardiac Anesthesia & Citical Care",
  "Critical Care",
  "Otologi",
  "Onkologi Bedah Kepala Leher",
  "Rinologi",
  "Bedah Anak Kolorektal Anak",
  "Bedah Onkologi Anak",
  "Pengelolaan Pra Transfusi",
  "Neuroradiologi Kepala dan Leher Anak",
  "Infeksi dan Tumor Rongga Toraks",
  "Onkologi Intervensional",
];

export const FUNDING = ["Biaya Kemkes", "Pribadi", "Kemkes", "LPDP"];
export const ALL_LABEL = "Total Peserta Fellowship";
export const STATUS_LABEL = {
  "akan pendidikan": "Peserta Akan Pendidikan",
  "sedang pendidikan": "Peserta Sedang Pendidikan",
  cuti: "Cuti",
  "telah lulus": "Telah Lulus",
};

export const PROVINCES = [
  "Aceh",
  "Sumatera Utara",
  "Sumatera Barat",
  "Riau",
  "Jambi",
  "Sumatera Selatan",
  "Bengkulu",
  "Lampung",
  "Kepulauan Bangka Belitung",
  "Kepulauan Riau",
  "DKI Jakarta",
  "Jawa Barat",
  "Jawa Tengah",
  "DI Yogyakarta",
  "Jawa Timur",
  "Banten",
  "Bali",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Kalimantan Barat",
  "Kalimantan Tengah",
  "Kalimantan Selatan",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Sulawesi Utara",
  "Sulawesi Tengah",
  "Sulawesi Selatan",
  "Sulawesi Tenggara",
  "Gorontalo",
  "Sulawesi Barat",
  "Maluku",
  "Maluku Utara",
  "Papua",
  "Papua Barat",
  "Papua Barat Daya",
  "Papua Selatan",
  "Papua Tengah",
  "Papua Pegunungan",
];
